version: '3.7'

# Define services
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - psql_data:/var/lib/postgresql/data

  app-server:
    image: go_api
    container_name: go_api
    build: ./
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test

  # Volumes
volumes:
  psql_data: